### PR TITLE
Fix emoji seeding race condition for meeting messages

### PR DESCRIPTION
**Pull request by QuantumManiac**
Fixed an issue where the "seed" emojis added by Minerva to meeting messages will be in the wrong order due to a race condition.

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva/45)

### CODE REVIEW

**Review by BluCodeGH — COMMENTED** [review]
I'm not convinced this will solve this issue. Since we're already awaiting the first request, the second one won't run until it finishes anyways, assigning the result to a variable shouldn't change that. I think we might need to add like a 1 second delay between the requests instead.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva/45#-:-MsBIn8tAr-MjLthux-R:bijryze)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrissank, @jlsajfj, @KavinSatheeskumar, and @wendi-yu)

**Review by BluCodeGH — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva/45#-:-MsBOET874U9UCWma0e9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrissank, @jlsajfj, @KavinSatheeskumar, and @wendi-yu)

**Review by QuantumManiac — COMMENTED** [review]
I might just be misremembering my async JS, but `await` doesn't seem to wait until the execution of the async function is finished unless it was done in that way I did. If you run the snippet below:
```js
const await1000 = async () => {
  setTimeout(() => {
    console.log(1000)
  }, 1000)
}

const await5000 = async () => {
  setTimeout(() => {
    console.log(5000)
  }, 5000)
}

const testFunction = async () => {
  await await5000()
  await await1000()

}

testFunction()
```
`1000` will be printed before `5000`. Maybe this is something completely different?

Nevertheless, I've added a 1 second delay on top of this.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva/45#-:-MsBNLEI6ellulbgXVKf:b-zdc4it)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrissank, @jlsajfj, @KavinSatheeskumar, and @wendi-yu)

**Review by BluCodeGH — COMMENTED** [review]
setTimeout returns immediately which is why your code runs in order. If you instead `await new Promise(r => setTimeout(r, 1000)); console.log(1000);` you should see the behavior I describe.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva/45#-:-MsBOWOU8nojAx3_Gu4A:b-qwx0cc)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrissank, @jlsajfj, @KavinSatheeskumar, and @wendi-yu)

**Pull request merged**
