### PR TITLE
Rewrite 

### PR DESCRIPTION
**Pull request by chrissank**
The rewrite is finally done! The switch to AWS has caused everything be updated and need to be reviewed. This is a good time for people to get to know how the project works.

Added in this PR are a ton of things:

- All commands that previously required the use of arguments such as: `/command arg1 arg2` now have a GUI form editor to make things easier
- Google Calendar event descriptions will need to be re-written to be updated to the JSON standard
- Switched from Firebase to AWS. Minerva should now be **much** faster than before.
- Added option to initialize events that contain an undefined description
- Added context and feedback for various commands, events
- Added context to messages sent to single-channel-guests
- Potentially fix HTML tag copy/paste issue

Note: neither github action currently works. 

- Right now unit tests appear to fail on GitHub because of a timezone issue, but they pass locally
- Auto deploy to AWS doesn't work. If approved before this is fixed, I will be able to manually deploy.

@jacobdeery, @wendi-yu: I haven't added you as reviewers, I know you're both busy. Let me know if you'd like to and I can add you.

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva/19)

### CODE REVIEW

**Review by jacobdeery — COMMENTED** [review]
This looks awesome, I'm really excited to get this in!

> Reviewed 55 of 55 files at r1.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva/19#-:-MNlGmKlE978d6MLSh0H:b-j7mpkj)* status: all files reviewed, 15 unresolved discussions (waiting on @chrissank, @Oasixer, @QuantumManiac, and @TieuKhang)

___
*[README.md, line 18 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/19#-MNlBWp_9I5fU88o2K4I:-MNlBWp_9I5fU88o2K4J:bsq8hn8) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/9ff54e3c0e6fd3912eddb9543d7b30557a11a2c0/README.md#L18)):*
> ```
> with a variety of parameters
> ```
are there still parameters?
___
*[README.md, line 18 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/19#-MNlBZLy1IpETBvINKXu:-MNlBZLy1IpETBvINKXv:b-qgv56h) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/9ff54e3c0e6fd3912eddb9543d7b30557a11a2c0/README.md#L18)):*
> ```
> This is restricted to admins only
> ```
Is this still the case?
___
*[__tests__/unit/calendar.test.js, line 1 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/19#-MNlBzQF3gKUx1n4ZLTe:-MNlBzQF3gKUx1n4ZLTf:bs93dk0) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/9ff54e3c0e6fd3912eddb9543d7b30557a11a2c0/__tests__/unit/calendar.test.js#L1)):*
> ```JavaScript
> //const test = require("firebase-functions-test")();
> ```

is this intentionally commented out?
___
*[__tests__/unit/calendar.test.js, line 17 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/19#-MNlBxGqDJHFGOy_rxcu:-MNlBxGqDJHFGOy_rxcv:b-pglvow) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/9ff54e3c0e6fd3912eddb9543d7b30557a11a2c0/__tests__/unit/calendar.test.js#L17)):*
<details><summary><i alt="summary">Quoted 10 lines of code…</i></summary>

> ```
> // test.mockConfig({
> //     slack: {
> //         token: "",
> //     },
> //     googleaccount: {
> //         client: "",
> //         secret: "",
> //         redirect: "",
> //     },
> // });
> ```
</details>

same as above
___
*[__tests__/unit/events.test.js, line 29 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/19#-MNlCQC_2jKeV060o1fR:-MNlCQC_2jKeV060o1fS:b-7xfcn9) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/9ff54e3c0e6fd3912eddb9543d7b30557a11a2c0/__tests__/unit/events.test.js#L29)):*
> ```JavaScript
>     describe("isEventSoon", function () {
>         it("check event already happened", async function () {
>             await expect(event.isEventSoon(-1)).to.be.rejectedWith("no-send");
> ```

You're using a mix of Chai's fluent style (`expect().to.be.rejectedWith`) and the classic `assert` style. Is this necessary because of the `await` stuff, or could these all be changed to the same style? Not essential, I just think it might be easier to read if we can make it consistent.
___
*[deploy/deploy_production.bat, line 4 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/19#-MNlDPRpDG9721JRV-nP:-MNlDPRq1uVpn_FvCsqe:byz77he) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/9ff54e3c0e6fd3912eddb9543d7b30557a11a2c0/deploy/deploy_production.bat#L4)):*
> ```Batchfile
> ECHO Tsk tsk. Deploying to production without approval?
> ECHO.
> ECHO If your branch is ready to be deployed to production, open a PR and request reviews. Once approved, the custom GitHub action will auto-deploy to production.
> ```

very nice
___
*[src/index.js, line 33 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/19#-MNlD_4D1tiPCTdbAPnu:-MNlD_4D1tiPCTdbAPnv:b1c39wb) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/9ff54e3c0e6fd3912eddb9543d7b30557a11a2c0/src/index.js#L33)):*
> ```
> Recieved
> ```
Received
___
*[src/commands/notify.js, line 28 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/19#-MNlFJP82xGZxMCS34P5:-MNlFJP82xGZxMCS34P6:b-1muqi3) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/9ff54e3c0e6fd3912eddb9543d7b30557a11a2c0/src/commands/notify.js#L28)):*
> ```
> recieve
> ```
receive
___
*[src/commands/notify.js, line 74 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/19#-MNlE6H_ATLfnM788-Z1:-MNlE6H_ATLfnM788-Z2:bz6aijn) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/9ff54e3c0e6fd3912eddb9543d7b30557a11a2c0/src/commands/notify.js#L74)):*
> ```
> waterloo rocketry
> ```
Waterloo Rocketry
___
*[src/commands/notify.js, line 83 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/19#-MNlE8F66c74YBy1SVLv:-MNlE8F66c74YBy1SVLw:bavqun0) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/9ff54e3c0e6fd3912eddb9543d7b30557a11a2c0/src/commands/notify.js#L83)):*
> ```
> messages
> ```
message's
___
*[src/commands/meeting/edit.js, line 31 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/19#-MNlF54EBzySP8ksjDXx:-MNlF54EBzySP8ksjDXy:b-1muqi3) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/9ff54e3c0e6fd3912eddb9543d7b30557a11a2c0/src/commands/meeting/edit.js#L31)):*
> ```
> recieve
> ```
receive
___
*[src/handlers/calendar-handler.js, line 59 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/19#-MNlEhm85K79CA0_3rVv:-MNlEhm85K79CA0_3rVw:b-9bt3zh) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/9ff54e3c0e6fd3912eddb9543d7b30557a11a2c0/src/handlers/calendar-handler.js#L59)):*
> ```JavaScript
>         let parameters;
>         try {
>             parameters = await this.getParametersFromDescription(event, require("./slack-handler").defaultChannels);
> ```

What would cause this to error?
___
*[src/interactivity/initialize.js, line 17 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/19#-MNlFbjv2sjqmXXm9Cv7:-MNlFbjv2sjqmXXm9Cv8:b-1muqi3) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/9ff54e3c0e6fd3912eddb9543d7b30557a11a2c0/src/interactivity/initialize.js#L17)):*
> ```
> recieve
> ```
receive
___
*[src/scheduled/events.js, line 22 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/19#-MNlFlqj2-euZELQfHvb:-MNlFlqj2-euZELQfHvc:btfc6lm) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/9ff54e3c0e6fd3912eddb9543d7b30557a11a2c0/src/scheduled/events.js#L22)):*
> ```JavaScript
>         const parameters = await calendar_handler.getParametersFromDescription(event, slack_handler.defaultChannels);
> 
>         const emojiPair = !isEventSoon && parameters.eventType === "meeting" ? await this.generateEmojiPair() : undefined;
> ```

can you put parens around `!isEventSoon && parameters.eventType === "meeting"`? Makes it slightly easier to read this line
___
*[src/scheduled/events.js, line 84 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/19#-MNlGD5EAyJOFzbLYWPC:-MNlG2o10eOlRqyksorr:bln3peh) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/9ff54e3c0e6fd3912eddb9543d7b30557a11a2c0/src/scheduled/events.js#L84)):*
> ```JavaScript
>         // prettier-ignore
>         message +=
> 		    "\nWays to attend:" +
> ```

Indent with spaces for consistency
___
*[src/scheduled/events.js, line 87 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/19#-MNlGERk0MBkVYecWdvO:-MNlGERk0MBkVYecWdvP:b-d5ok0j) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/9ff54e3c0e6fd3912eddb9543d7b30557a11a2c0/src/scheduled/events.js#L87)):*
> ```
> 		    "\n      :office: In person @ " + event.location +
> 		    "\n      :globe_with_meridians: Online @ " + parameters.link +
> 		    "\n      :calling: By phone +1-437-538-3987 (2633 1815 39)";
> ```
Should we make this a bit more flexible? I think we can at least check if location is undefined, and leave the `In person` out if so. Maybe also only include the phone number if the meeting is in bay_area?

**Review by chrissank — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva/19)* status: 43 of 55 files reviewed, 15 unresolved discussions (waiting on @jacobdeery, @Oasixer, @QuantumManiac, and @TieuKhang)

___
*[README.md, line 18 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/19#-MNlBWp_9I5fU88o2K4I:-MNpFxkX2vhRc4RJLiyW:b-jynerz) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/9ff54e3c0e6fd3912eddb9543d7b30557a11a2c0/README.md#L18)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> with a variety of parameters
> ```
are there still parameters?
</blockquote></details>

Nope. Replaced.
___
*[README.md, line 18 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/19#-MNlBZLy1IpETBvINKXu:-MNpG-3m1-wS2DC2uz_4:b-yj3bht) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/9ff54e3c0e6fd3912eddb9543d7b30557a11a2c0/README.md#L18)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> This is restricted to admins only
> ```
Is this still the case?
</blockquote></details>

Yes. Does it need to be? I'm open to removing this requirement.
___
*[__tests__/unit/calendar.test.js, line 1 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/19#-MNlBzQF3gKUx1n4ZLTe:-MNpG9MDBgiWgNEWufMp:bt2vr1b) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/9ff54e3c0e6fd3912eddb9543d7b30557a11a2c0/__tests__/unit/calendar.test.js#L1)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

is this intentionally commented out?
</blockquote></details>

Fixed.
___
*[__tests__/unit/calendar.test.js, line 17 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/19#-MNlBxGqDJHFGOy_rxcu:-MNpG7uGB1uJvd63XpMl:bt2vr1b) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/9ff54e3c0e6fd3912eddb9543d7b30557a11a2c0/__tests__/unit/calendar.test.js#L17)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> // test.mockConfig({
> //     slack: {
> //         token: "",
> //     },
> //     googleaccount: {
> //         client: "",
> //         secret: "",
> //         redirect: "",
> //     },
> // });
> ```
same as above
</blockquote></details>

Fixed.
___
*[__tests__/unit/events.test.js, line 29 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/19#-MNlCQC_2jKeV060o1fR:-MNpGBOK2qOH_AQ4zQVa:bhhbqgz) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/9ff54e3c0e6fd3912eddb9543d7b30557a11a2c0/__tests__/unit/events.test.js#L29)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

You're using a mix of Chai's fluent style (`expect().to.be.rejectedWith`) and the classic `assert` style. Is this necessary because of the `await` stuff, or could these all be changed to the same style? Not essential, I just think it might be easier to read if we can make it consistent.
</blockquote></details>

I believe this is necessary because of the 'await' stuff. I believe this is required because of the `chai-as-promised` module that I found to work with async functions. I'll look into this in the future if there's a more consistent way to do things. 
___
*[src/index.js, line 33 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/19#-MNlD_4D1tiPCTdbAPnu:-MNpGUpe1OdRvesLfxC_:b-lx4fj3) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/9ff54e3c0e6fd3912eddb9543d7b30557a11a2c0/src/index.js#L33)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> Recieved
> ```
Received
</blockquote></details>

Fixed. 
___
*[src/commands/notify.js, line 28 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/19#-MNlFJP82xGZxMCS34P5:-MNpHD3e1Wm-HOWoYD5c:b-lx4fj3) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/9ff54e3c0e6fd3912eddb9543d7b30557a11a2c0/src/commands/notify.js#L28)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> recieve
> ```
receive
</blockquote></details>

Fixed. 
___
*[src/commands/notify.js, line 74 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/19#-MNlE6H_ATLfnM788-Z1:-MNpGXZ23NVt9yR9PtW0:b3ebdpm) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/9ff54e3c0e6fd3912eddb9543d7b30557a11a2c0/src/commands/notify.js#L74)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> waterloo rocketry
> ```
Waterloo Rocketry
</blockquote></details>

Fixed, added that it needs to be a Waterloo Rocketry slack message.
___
*[src/commands/notify.js, line 83 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/19#-MNlE8F66c74YBy1SVLv:-MNpGaee290nSVX7JfDj:b-lx4fj3) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/9ff54e3c0e6fd3912eddb9543d7b30557a11a2c0/src/commands/notify.js#L83)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> messages
> ```
message's
</blockquote></details>

Fixed. 
___
*[src/commands/meeting/edit.js, line 31 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/19#-MNlF54EBzySP8ksjDXx:-MNpGi5i9ji9NXWDfhN0:b-lx4fj3) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/9ff54e3c0e6fd3912eddb9543d7b30557a11a2c0/src/commands/meeting/edit.js#L31)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> recieve
> ```
receive
</blockquote></details>

Fixed. 
___
*[src/handlers/calendar-handler.js, line 59 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/19#-MNlEhm85K79CA0_3rVv:-MNpGjNNCW097g6ZT5r0:b-dwjl87) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/9ff54e3c0e6fd3912eddb9543d7b30557a11a2c0/src/handlers/calendar-handler.js#L59)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

What would cause this to error?
</blockquote></details>

Print line was there to debug, it's been removed. We require the try-catch otherwise if the event `rejects` (i.e. if the event has a malformed description, etc.)  we don't want it to return the entire function, just within the try-catch. That way if an event has a malformed description it doesn't block any of the other events it needs to check from being checked.
___
*[src/interactivity/initialize.js, line 17 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/19#-MNlFbjv2sjqmXXm9Cv7:-MNpH0T60mHYnyZ8pk4Y:b-lx4fj3) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/9ff54e3c0e6fd3912eddb9543d7b30557a11a2c0/src/interactivity/initialize.js#L17)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> recieve
> ```
receive
</blockquote></details>

Fixed. 
___
*[src/scheduled/events.js, line 22 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/19#-MNlFlqj2-euZELQfHvb:-MNpH1BVAtVcXJ2LWQJS:b-halo1w) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/9ff54e3c0e6fd3912eddb9543d7b30557a11a2c0/src/scheduled/events.js#L22)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

can you put parens around `!isEventSoon && parameters.eventType === "meeting"`? Makes it slightly easier to read this line
</blockquote></details>

Done. It was this way originally, but the formatter removed them.
___
*[src/scheduled/events.js, line 84 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/19#-MNlGD5EAyJOFzbLYWPC:-MNpH4x8Cu6eY3Jk3gHV:b-lx4fj3) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/9ff54e3c0e6fd3912eddb9543d7b30557a11a2c0/src/scheduled/events.js#L84)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

Indent with spaces for consistency
</blockquote></details>

Fixed. 
___
*[src/scheduled/events.js, line 87 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/19#-MNlGERk0MBkVYecWdvO:-MNpH5KS-mLB1rldlyPO:b-vyqe3g) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/9ff54e3c0e6fd3912eddb9543d7b30557a11a2c0/src/scheduled/events.js#L87)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> 		    "\n      :office: In person @ " + event.location +
> 		    "\n      :globe_with_meridians: Online @ " + parameters.link +
> 		    "\n      :calling: By phone +1-437-538-3987 (2633 1815 39)";
> ```
Should we make this a bit more flexible? I think we can at least check if location is undefined, and leave the `In person` out if so. Maybe also only include the phone number if the meeting is in bay_area?
</blockquote></details>

Added what you said, required a new unit test and they were adjusted accordingly.

**Review by jacobdeery — APPROVED** [review]
I'm happy with this PR as is; I'll leave it up to you if you want to merge or if you want someone else to take a look.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva/19#-:-MNpJyS69WFcypSitUFF:bmr5fub)* status: 43 of 55 files reviewed, 3 unresolved discussions (waiting on @chrissank, @jacobdeery, @Oasixer, @QuantumManiac, and @TieuKhang)

___
*[__tests__/unit/events.test.js, line 29 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/19#-MNlCQC_2jKeV060o1fR:-MNpJ4Hc30I3nxBs1VLW:b-hfghm4) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/9ff54e3c0e6fd3912eddb9543d7b30557a11a2c0/__tests__/unit/events.test.js#L29)):*
<details><summary><i>Previously, chrissank (Chris Sankey) wrote…</i></summary><blockquote>

I believe this is necessary because of the 'await' stuff. I believe this is required because of the `chai-as-promised` module that I found to work with async functions. I'll look into this in the future if there's a more consistent way to do things. 
</blockquote></details>

Sounds good
___
*[src/handlers/calendar-handler.js, line 59 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/19#-MNlEhm85K79CA0_3rVv:-MNpJTdk4pkMSOXMls6a:bb0oaxu) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/9ff54e3c0e6fd3912eddb9543d7b30557a11a2c0/src/handlers/calendar-handler.js#L59)):*
<details><summary><i>Previously, chrissank (Chris Sankey) wrote…</i></summary><blockquote>

Print line was there to debug, it's been removed. We require the try-catch otherwise if the event `rejects` (i.e. if the event has a malformed description, etc.)  we don't want it to return the entire function, just within the try-catch. That way if an event has a malformed description it doesn't block any of the other events it needs to check from being checked.
</blockquote></details>

If an event has a malformed description, we'll still get notified about it by `getParametersFromDescription` - is that correct?
___
*[src/scheduled/events.js, line 87 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/19#-MNlGERk0MBkVYecWdvO:-MNpJfG-CaijOiJDFJtb:b-zdop1) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/9ff54e3c0e6fd3912eddb9543d7b30557a11a2c0/src/scheduled/events.js#L87)):*
<details><summary><i>Previously, chrissank (Chris Sankey) wrote…</i></summary><blockquote>

Added what you said, required a new unit test and they were adjusted accordingly.
</blockquote></details>

Awesome, looks good

**Review by QuantumManiac — APPROVED** [review]
> Reviewed 15 of 15 files at r2.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva/19)* status: all files reviewed, 3 unresolved discussions (waiting on @chrissank, @jacobdeery, @Oasixer, and @TieuKhang)

**Review by chrissank — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva/19)* status: 54 of 56 files reviewed, 3 unresolved discussions (waiting on @chrissank, @jacobdeery, @Oasixer, @QuantumManiac, and @TieuKhang)

___
*[src/handlers/calendar-handler.js, line 59 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/19#-MNlEhm85K79CA0_3rVv:-MPHsQsx9MI998BrhtJw:badp9k8) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/9ff54e3c0e6fd3912eddb9543d7b30557a11a2c0/src/handlers/calendar-handler.js#L59)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

If an event has a malformed description, we'll still get notified about it by `getParametersFromDescription` - is that correct?
</blockquote></details>

I never actually responded to this, but yes, we will still get the malformed errors just as before. As I typed this I realized we should also check for this on the nightly initialize check. I will add this as an issue to do another time.

**Pull request merged**
