### PR TITLE
Better description

### PR DESCRIPTION
**Pull request by chrissank**
Add indentation and line breaks, change from channel IDs to channel names

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva/22)

### CODE REVIEW

**Review by jacobdeery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva/22)* status: 0 of 8 files reviewed, 6 unresolved discussions (waiting on @chrissank, @jacobdeery, and @QuantumManiac)

___
*[.gitignore, line 73 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/22#-MQTtoJlE9ef3fkzq5nz:-MQTtoJlE9ef3fkzq5o-:bgrs2qo) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/b12f07ed5c2a79aa6f055e569de07c7ec6c81969/.gitignore#L73)):*
> ```ignore
> .idea/
> 
> /deploy/deploy_variables.bat
> ```

Newline at EOF
___
*[__tests__/unit/calendar.test.js, line 13 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/22#-MQTtzdD2kSOd3d_YEed:-MQTtzdD2kSOd3d_YEee:bhiqhl6) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/b12f07ed5c2a79aa6f055e569de07c7ec6c81969/__tests__/unit/calendar.test.js#L13)):*
> ```JavaScript
> const UPPER_BOUND = 21600000; // 6 hours in milliseconds
> 
> const channelIDMapping = new Map();
> ```

Have I ever mentioned that I hate how `const` works in JS?

(no action required here)
___
*[src/commands/meeting.js, line 7 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/22#-MQTuUUi6RA1IrM-5qOx:-MQTuUUj4mJi9UxKpa2x:byp6rt5) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/b12f07ed5c2a79aa6f055e569de07c7ec6c81969/src/commands/meeting.js#L7)):*
> ```JavaScript
>         return require("./meeting/edit").send(originChannelID, trigger);
>     } else {
>         return Promise.reject("Incorrect usage: /reminder <reminder/edit>");
> ```

Revert
___
*[src/commands/meeting/edit.js, line 44 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/22#-MQTvCSD7EWU2FKlVnLi:-MQTvCSD7EWU2FKlVnLj:b-3olypa) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/b12f07ed5c2a79aa6f055e569de07c7ec6c81969/src/commands/meeting/edit.js#L44)):*
> ```JavaScript
>     // convert back to channel names
>     // this could definitely could be made better
>     var channelIdMapping = await slack_handler.generateChannelNameIdMapping();
> ```

We can just create a mapping from ID -> name and use that instead of these for loop shenanigans.
___
*[src/commands/meeting/edit.js, line 52 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/22#-MQTuh64DqN8z-qTE8Hw:-MQTuh64DqN8z-qTE8Hx:b-xo7t46) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/b12f07ed5c2a79aa6f055e569de07c7ec6c81969/src/commands/meeting/edit.js#L52)):*
> ```JavaScript
>     }
> 
>     parameters.mainChannel = parameters.mainChannel;
> ```

What does this line do?
___
*[src/handlers/calendar-handler.js, line 110 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/22#-MQTvXayCZLKFfdCZbhv:-MQTvXayCZLKFfdCZbhw:b3hij1k) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/b12f07ed5c2a79aa6f055e569de07c7ec6c81969/src/handlers/calendar-handler.js#L110)):*
> ```
> !channelIdMapping.has(parameters.mainChannel)
> ```
This will only happen if `mainChannel` was specified but invalid, correct? If so, erroring with the message "Upcoming meeting is missing a mainChannel element" is misleading.
___
*[src/handlers/calendar-handler.js, line 128 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/22#-MQTw4zJEiMK9sNjj5ot:-MQTw4zJEiMK9sNjj5ou:b5lay4b) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/b12f07ed5c2a79aa6f055e569de07c7ec6c81969/src/handlers/calendar-handler.js#L128)):*
> ```JavaScript
>             parameters.additionalChannels[channelKey] = channelIdMapping.get(parameters.additionalChannels[channelKey]);
>         } else {
>             parameters.additionalChannels.splice(channelKey, 1);
> ```

It bothers me slightly that we silently suppress this issue here. Is there any way we can log a warning?

**Review by chrissank — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva/22)* status: 0 of 10 files reviewed, 6 unresolved discussions (waiting on @jacobdeery and @QuantumManiac)

___
*[.gitignore, line 73 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/22#-MQTtoJlE9ef3fkzq5nz:-MQU8fqz6evbhCburjvD:b-886gsx) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/b12f07ed5c2a79aa6f055e569de07c7ec6c81969/.gitignore#L73)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

Newline at EOF
</blockquote></details>

Fixed
___
*[src/commands/meeting.js, line 7 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/22#-MQTuUUi6RA1IrM-5qOx:-MQU8iUSDTEBaKVS0YCG:b-886gsx) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/b12f07ed5c2a79aa6f055e569de07c7ec6c81969/src/commands/meeting.js#L7)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

Revert
</blockquote></details>

Fixed
___
*[src/commands/meeting/edit.js, line 44 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/22#-MQTvCSD7EWU2FKlVnLi:-MQU8jR_9M_WIb-WSLS0:b-r1kkph) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/b12f07ed5c2a79aa6f055e569de07c7ec6c81969/src/commands/meeting/edit.js#L44)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

We can just create a mapping from ID -> name and use that instead of these for loop shenanigans.
</blockquote></details>

Fixed. I added it to the same mapping so as to not change the functionality of `generateChannelIdMapping`.
___
*[src/commands/meeting/edit.js, line 52 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/22#-MQTuh64DqN8z-qTE8Hw:-MQU8usG4aLknTqbB8kq:b-y6q3nh) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/b12f07ed5c2a79aa6f055e569de07c7ec6c81969/src/commands/meeting/edit.js#L52)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

What does this line do?
</blockquote></details>

Not really sure lol, removed.
___
*[src/handlers/calendar-handler.js, line 110 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/22#-MQTvXayCZLKFfdCZbhv:-MQU8wdR5DqexqU1vnFH:bt2vr1b) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/b12f07ed5c2a79aa6f055e569de07c7ec6c81969/src/handlers/calendar-handler.js#L110)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> !channelIdMapping.has(parameters.mainChannel)
> ```
This will only happen if `mainChannel` was specified but invalid, correct? If so, erroring with the message "Upcoming meeting is missing a mainChannel element" is misleading.
</blockquote></details>

Fixed.
___
*[src/handlers/calendar-handler.js, line 128 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/22#-MQTw4zJEiMK9sNjj5ot:-MQU8xvgDfkN5HJDQ9GR:b-i8gt8o) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/b12f07ed5c2a79aa6f055e569de07c7ec6c81969/src/handlers/calendar-handler.js#L128)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

It bothers me slightly that we silently suppress this issue here. Is there any way we can log a warning?
</blockquote></details>

Added a warning

**Review by jacobdeery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva/22)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @chrissank and @QuantumManiac)

___
*[src/commands/meeting/edit.js, line 44 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/22#-MQTvCSD7EWU2FKlVnLi:-MQUGbP2BK4lSJO94dQ3:b279b1w) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/b12f07ed5c2a79aa6f055e569de07c7ec6c81969/src/commands/meeting/edit.js#L44)):*
<details><summary><i>Previously, chrissank (Chris Sankey) wrote…</i></summary><blockquote>

Fixed. I added it to the same mapping so as to not change the functionality of `generateChannelIdMapping`.
</blockquote></details>

I don't think we want them in the same mapping. The keys should all be from the same semantic category. I would suggest leaving `generateChannelIdMapping` untouched and just making a new function that generates the reverse mapping.
___
*[src/handlers/calendar-handler.js, line 111 at r2](https://reviewable.io/reviews/waterloo-rocketry/minerva/22#-MQUHEUa9Q-yhY--csLI:-MQUHEUa9Q-yhY--csLJ:b2s0hs8) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/dffc92a5cb979bce394b4b4bb9be1edc499894fd/src/handlers/calendar-handler.js#L111)):*
> ```
> a 
> ```
remove

**Review by chrissank — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva/22)* status: 0 of 11 files reviewed, 2 unresolved discussions (waiting on @jacobdeery and @QuantumManiac)

___
*[src/commands/meeting/edit.js, line 44 at r1](https://reviewable.io/reviews/waterloo-rocketry/minerva/22#-MQTvCSD7EWU2FKlVnLi:-MQXMpI-2Om5JhUUvGn1:bb6un1j) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/b12f07ed5c2a79aa6f055e569de07c7ec6c81969/src/commands/meeting/edit.js#L44)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

I don't think we want them in the same mapping. The keys should all be from the same semantic category. I would suggest leaving `generateChannelIdMapping` untouched and just making a new function that generates the reverse mapping.
</blockquote></details>

Done
___
*[src/handlers/calendar-handler.js, line 111 at r2](https://reviewable.io/reviews/waterloo-rocketry/minerva/22#-MQUHEUa9Q-yhY--csLI:-MQXMreNCdITuIdIA-am:bb6un1j) ([raw file](https://github.com/waterloo-rocketry/minerva/blob/dffc92a5cb979bce394b4b4bb9be1edc499894fd/src/handlers/calendar-handler.js#L111)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> a 
> ```
remove
</blockquote></details>

Done

**Review by jacobdeery — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva/22)* status: 0 of 11 files reviewed, all discussions resolved (waiting on @QuantumManiac)

**Review by QuantumManiac — APPROVED** [review]
> Reviewed 2 of 8 files at r1, 3 of 8 files at r2, 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/minerva/22)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrissank)

**Pull request merged**
